spring:
  datasource:
    url: jdbc:mysql://172.17.128.231:3306/lecai2_dd?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&autoReconnect=true
    #    url: jdbc:mysql://192.168.199.201:3306/lecai2_dd?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pwdasdwx
    #    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
logging:
  level:
    root: info
    com.ibootz: debug
    com.ibootz.demomybatis.mapper: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ibootz.demomybatis.model
  configuration:
    # 完全关闭mybatis默认开启的一级缓存和二级缓存，可以考虑使用SpringCache全局缓存代替
    local-cache-scope: STATEMENT
    cache-enabled: false
server:
  port: 6080